apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app-dpl
  labels:
    app: time
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "20%"
      maxUnavailable: "10%"
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels:
        env: demo
    spec:
      containers:
      - name: time-app
        image: anestesia01/k8s-demo:time-app-1.0.0
        ports:
          - containerPort: 8000
